/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/bulletin_board': RouteRecordInfo<'/dashboard/bulletin_board', '/dashboard/bulletin_board', Record<never, never>, Record<never, never>>,
    '/dashboard/parking/reservation': RouteRecordInfo<'/dashboard/parking/reservation', '/dashboard/parking/reservation', Record<never, never>, Record<never, never>>,
    '/dashboard/parking/reservation_history': RouteRecordInfo<'/dashboard/parking/reservation_history', '/dashboard/parking/reservation_history', Record<never, never>, Record<never, never>>,
    '/dashboard/passage/list': RouteRecordInfo<'/dashboard/passage/list', '/dashboard/passage/list', Record<never, never>, Record<never, never>>,
    '/dashboard/passage/statistics': RouteRecordInfo<'/dashboard/passage/statistics', '/dashboard/passage/statistics', Record<never, never>, Record<never, never>>,
    '/dashboard/profile': RouteRecordInfo<'/dashboard/profile', '/dashboard/profile', Record<never, never>, Record<never, never>>,
    '/dashboard/user': RouteRecordInfo<'/dashboard/user', '/dashboard/user', Record<never, never>, Record<never, never>>,
    '/dashboard/vehicle/list': RouteRecordInfo<'/dashboard/vehicle/list', '/dashboard/vehicle/list', Record<never, never>, Record<never, never>>,
    '/dashboard/vehicle/register': RouteRecordInfo<'/dashboard/vehicle/register', '/dashboard/vehicle/register', Record<never, never>, Record<never, never>>,
    '/dashboard/visit/reservation': RouteRecordInfo<'/dashboard/visit/reservation', '/dashboard/visit/reservation', Record<never, never>, Record<never, never>>,
    '/dashboard/visit/reservation_history': RouteRecordInfo<'/dashboard/visit/reservation_history', '/dashboard/visit/reservation_history', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
  }
}
