/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/activity/application': RouteRecordInfo<'/admin/activity/application', '/admin/activity/application', Record<never, never>, Record<never, never>>,
    '/admin/activity/info': RouteRecordInfo<'/admin/activity/info', '/admin/activity/info', Record<never, never>, Record<never, never>>,
    '/admin/user/info': RouteRecordInfo<'/admin/user/info', '/admin/user/info', Record<never, never>, Record<never, never>>,
    '/admin/user/volunteer_hour': RouteRecordInfo<'/admin/user/volunteer_hour', '/admin/user/volunteer_hour', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/activity/': RouteRecordInfo<'/dashboard/activity/', '/dashboard/activity', Record<never, never>, Record<never, never>>,
    '/dashboard/activity/[id]': RouteRecordInfo<'/dashboard/activity/[id]', '/dashboard/activity/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/bulletin_board': RouteRecordInfo<'/dashboard/bulletin_board', '/dashboard/bulletin_board', Record<never, never>, Record<never, never>>,
    '/dashboard/user_center': RouteRecordInfo<'/dashboard/user_center', '/dashboard/user_center', Record<never, never>, Record<never, never>>,
    '/dashboard/user_center/activity': RouteRecordInfo<'/dashboard/user_center/activity', '/dashboard/user_center/activity', Record<never, never>, Record<never, never>>,
    '/dashboard/user_center/apply': RouteRecordInfo<'/dashboard/user_center/apply', '/dashboard/user_center/apply', Record<never, never>, Record<never, never>>,
    '/dashboard/user_center/password': RouteRecordInfo<'/dashboard/user_center/password', '/dashboard/user_center/password', Record<never, never>, Record<never, never>>,
    '/dashboard/user_center/profile': RouteRecordInfo<'/dashboard/user_center/profile', '/dashboard/user_center/profile', Record<never, never>, Record<never, never>>,
    '/dashboard/user_center/volunteer_hour': RouteRecordInfo<'/dashboard/user_center/volunteer_hour', '/dashboard/user_center/volunteer_hour', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
  }
}
